# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/Send_Recv_Area.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(416, 368)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.clear_recv_area_btn = QtWidgets.QPushButton(self.groupBox)
        self.clear_recv_area_btn.setObjectName("clear_recv_area_btn")
        self.gridLayout.addWidget(self.clear_recv_area_btn, 2, 0, 1, 1)
        self.hex_recv_mode = QtWidgets.QRadioButton(self.groupBox)
        self.hex_recv_mode.setObjectName("hex_recv_mode")
        self.gridLayout.addWidget(self.hex_recv_mode, 1, 0, 1, 1)
        self.text_recv_mode = QtWidgets.QRadioButton(self.groupBox)
        self.text_recv_mode.setObjectName("text_recv_mode")
        self.gridLayout.addWidget(self.text_recv_mode, 0, 0, 1, 1)
        self.save_data_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_data_btn.setObjectName("save_data_btn")
        self.gridLayout.addWidget(self.save_data_btn, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.recv_area = QtWidgets.QTextBrowser(self.groupBox)
        self.recv_area.setObjectName("recv_area")
        self.horizontalLayout.addWidget(self.recv_area)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.send_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 4, 0, 1, 1)
        self.text_send_mode = QtWidgets.QRadioButton(self.groupBox_2)
        self.text_send_mode.setObjectName("text_send_mode")
        self.gridLayout_2.addWidget(self.text_send_mode, 0, 0, 1, 1)
        self.clear_send_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_send_btn.setObjectName("clear_send_btn")
        self.gridLayout_2.addWidget(self.clear_send_btn, 3, 0, 1, 1)
        self.hex_send_mode = QtWidgets.QRadioButton(self.groupBox_2)
        self.hex_send_mode.setObjectName("hex_send_mode")
        self.gridLayout_2.addWidget(self.hex_send_mode, 1, 0, 1, 1)
        self.send_file_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.send_file_btn.setObjectName("send_file_btn")
        self.gridLayout_2.addWidget(self.send_file_btn, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.send_area = QtWidgets.QTextEdit(self.groupBox_2)
        self.send_area.setObjectName("send_area")
        self.horizontalLayout_2.addWidget(self.send_area)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "接收区"))
        self.clear_recv_area_btn.setText(_translate("Dialog", "清空接收区"))
        self.hex_recv_mode.setText(_translate("Dialog", "hex模式"))
        self.text_recv_mode.setText(_translate("Dialog", "文本模式"))
        self.save_data_btn.setText(_translate("Dialog", "保存数据"))
        self.groupBox_2.setTitle(_translate("Dialog", "发送区"))
        self.send_btn.setText(_translate("Dialog", "发送"))
        self.text_send_mode.setText(_translate("Dialog", "文本模式"))
        self.clear_send_btn.setText(_translate("Dialog", "清空发送区"))
        self.hex_send_mode.setText(_translate("Dialog", "hex模式"))
        self.send_file_btn.setText(_translate("Dialog", "发送数据文件"))
